language: csharp
mono: none
dotnet: 2.1.401
install:
 - (cd Images.Web && npm install)
 - dotnet tool install --tool-path tools coveralls.net
script:
 - dotnet --info
 - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
 - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
 - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
 - echo $TRAVIS_COMMIT
 - echo $TRAVIS_BRANCH
 - echo $REPO_COMMIT_AUTHOR
 - echo $REPO_COMMIT_AUTHOR_EMAIL
 - echo $REPO_COMMIT_MESSAGE
 - echo $TRAVIS_JOB_ID
 - dotnet build
 - dotnet test ./Images.Tests/Images.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - ./tools/csmacnz.Coveralls --opencover -i ./Images.Tests/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci"  --useRelativePaths